/**
 * Regenerates src/styles.ts from the CSS sources, so the stylesheet can be
 * injected at runtime without a CSS loader in the build.
 *
 *   node scripts/build-styles.mjs
 */
import {readFileSync, writeFileSync} from 'node:fs'
import {dirname, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const read = (file) => readFileSync(resolve(root, file), 'utf8')

const css = [
  read('src/assets/css/pdf-remediation.css'),
  read('src/assets/css/studio-layer.css'),
].join('\n')

// Escape for a JS template literal.
const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

const out = `/**
 * Scoped stylesheet for the SkynetA11y PDF Remediation workspace.
 *
 * GENERATED by scripts/build-styles.mjs from:
 *   - src/assets/css/pdf-remediation.css  (the HTML build's stylesheet, scoped
 *     under .aiopdf-app, with the standalone \`body\` rules removed)
 *   - src/assets/css/studio-layer.css     (Sanity Studio integration layer)
 *
 * Edit those files and re-run \`npm run styles\` rather than editing this one.
 * Injected at runtime by PdfRemediationPage and removed on unmount.
 */

export const PDF_REMEDIATION_CSS: string = \`
${escaped}\`
`

writeFileSync(resolve(root, 'src/styles.ts'), out)
process.stdout.write(`Wrote src/styles.ts (${css.length} chars)\n`)
